### PR TITLE
Fixed France and Norway ISO 3 Codes

### PR DESCRIPTION
**Pull request by bdeining**

### CODE REVIEW

**Comment by bdeining** [comment]
@lexman any chance we could merge this?  Seems like there is interest from other parties

**Comment by bdeining** [comment]
@zelima

**Comment by bdeining** [comment]
https://github.com/datasets/geo-countries/issues/5

**Comment by ioquatix** [comment]
Yes please merge

**Comment by Mikanebu** [comment]
@bdeining Thanks a lot for your contribution, I am also going to close https://github.com/datasets/geo-countries/issues/5

**Pull request merged**
